USE [master]
GO

/****** Object:  Database [ArtsofteTestProject]    Script Date: 26.12.2022, понедельник 13:39:06 ******/
CREATE DATABASE [ArtsofteTestProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ArtsofteTestProject', FILENAME = N'C:\Users\Michaellux.DESKTOP-MUO1A9P\ArtsofteTestProject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ArtsofteTestProject_log', FILENAME = N'C:\Users\Michaellux.DESKTOP-MUO1A9P\ArtsofteTestProject_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ArtsofteTestProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ArtsofteTestProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ArtsofteTestProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ArtsofteTestProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ArtsofteTestProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ArtsofteTestProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ArtsofteTestProject] SET  MULTI_USER 
GO

ALTER DATABASE [ArtsofteTestProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ArtsofteTestProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ArtsofteTestProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ArtsofteTestProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ArtsofteTestProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ArtsofteTestProject] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ArtsofteTestProject] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ArtsofteTestProject] SET  READ_WRITE 
GO

