// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ArtsofteTestProject.Models;

public partial class EmployeePlace
{
    public Guid Id { get; set; }

    public Guid EmployeeId { get; set; }

    public Guid DepartmentId { get; set; }

    public Guid ProgrammingLanguageId { get; set; }

    public virtual Department Department { get; set; }

    public virtual Employee Employee { get; set; }

    [Display(Name = "Programming language")]
    public virtual ProgrammingLanguage ProgrammingLanguage { get; set; }
}