// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ArtsofteTestProject.Models
{
    public partial class GetAllProgrammingLanguagesResult
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }
}
