// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ArtsofteTestProject.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ArtsofteTestProject.Models
{
    public partial interface IArtsofteTestProjectContextProcedures
    {
        Task<int> DeleteEmployeePlaceAsync(Guid? pId, OutputParameter<int?> outerrornumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllDepartmentsResult>> GetAllDepartmentsAsync(OutputParameter<int?> outerrornumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllEmployeeResult>> GetAllEmployeeAsync(OutputParameter<int?> outerrornumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllProgrammingLanguagesResult>> GetAllProgrammingLanguagesAsync(OutputParameter<int?> outerrornumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetEmployeeResult>> GetEmployeeAsync(Guid? pId, OutputParameter<int?> outerrornumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetEmployeePlaceResult>> GetEmployeePlaceAsync(Guid? pId, OutputParameter<int?> outerrornumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> InsertEmployeeAsync(Guid? pId, string pName, string pSurname, int? pAge, string pGender, OutputParameter<int?> outerrornumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> InsertEmployeePlaceAsync(Guid? pId, Guid? pEmployeeId, Guid? pDepartmentId, Guid? pProgrammingLanguageId, OutputParameter<int?> outerrornumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateEmployeeAsync(Guid? pId, string pName, string pSurname, int? pAge, string pGender, OutputParameter<int?> outerrornumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateEmployeePlaceAsync(Guid? pId, Guid? pEmployeeId, Guid? pDepartmentId, Guid? pProgrammingLanguageId, OutputParameter<int?> outerrornumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
